# Generated by Django 4.0.7 on 2022-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image_alter_user_bio_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('T', ''), ('S', '')], default='S', max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='عکس'),
        ),
    ]
