# Generated by Django 4.0.6 on 2022-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_first_day_alter_course_second_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='first_day',
            field=models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_day',
            field=models.IntegerField(blank=True, choices=[(None, 'ندارد'), (0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه')], default=None, null=True),
        ),
    ]
